export const words = [
  { en: 'Growth', uz: 'o‘sish' },
  { en: 'Built-up', uz: 'qurilgan' },
  { en: 'A shame', uz: 'uyat' },
  { en: 'Pity', uz: 'achinish, rahm' },
  { en: 'Region', uz: 'mintaqa' },
  { en: 'Substantial', uz: 'muhim' },
  { en: 'Impressive', uz: 'ta’sirli' },
  { en: 'Semi-detached', uz: 'yarim bog‘langan' },
  { en: 'Original', uz: 'asli, dastlabki' },
  { en: 'Feature', uz: 'hususiyat, fazilat' },
  { en: 'Lead', uz: 'boshlamoq' },
  { en: 'Walled', uz: 'devor bilan qoplangan' },
  { en: 'Wall', uz: 'devor' },
  { en: 'Brick', uz: 'g‘isht' },
  { en: 'Stone', uz: 'tosh' },
  { en: 'Chimney', uz: 'mo‘ri' },
  { en: 'Roof', uz: 'tom' },
  { en: 'Shutter', uz: 'deraza eshigi' },
  { en: 'Hall', uz: 'zal' },
  { en: 'Passage', uz: 'yo‘lak' },
  { en: 'Corridor', uz: 'kalidor' },
  { en: 'Rubber tyre', uz: 'rezina shina' },
  { en: 'Woollen blanket', uz: 'jun ko‘rpa' },
  { en: 'Plastic toys', uz: 'plastik o‘yinchoqlar' },
  { en: 'Metal ladder', uz: 'metal narvon' },
  { en: 'Wax candle', uz: 'mum sham' },
  { en: 'Silver candlestick', uz: 'kumush shamdon' },
  { en: 'Gold medal', uz: 'oltin medal' },
  { en: 'Cardboard box', uz: 'karton quti' },
  { en: 'Steel pipe', uz: 'po‘lat truba' },
  { en: 'Concrete bridge', uz: 'beton ko‘prik' },
  { en: 'Iron railings', uz: 'temir panjaralar' },
  { en: 'Wooden fence', uz: 'yog‘och to‘siq' },
  { en: 'Circle', uz: 'doira' },
  { en: 'Round', uz: 'yumaloq' },
  { en: 'Spacious', uz: 'keng' },
  { en: 'Enormous', uz: 'katta, ulkan' },
  { en: 'Staircase', uz: 'zina, zinapoya' },
  { en: 'Attic', uz: 'cherdak, bolxona' },
  { en: 'Basement', uz: 'podval' },
  { en: 'Convert sth into sth', uz: 'nimanidir nimagadir o‘zgartirish' },
  { en: 'Separate', uz: 'ajralgan, alohida' },
  { en: 'Cellar', uz: 'yer to‘la' },
  { en: 'Currently', uz: 'hozirda, at the moment' },
  { en: 'Store sth', uz: 'nimanidir saqlab qo‘yish' },
  { en: 'Storage', uz: 'saqlash' },
  { en: 'Lawn', uz: 'gazon, maysazor' },
  { en: 'Drive', uz: 'xiyobon' },
  { en: 'Circular', uz: 'dumaloq' },
  { en: 'Square', uz: 'kvadrat' },
  { en: 'Rectangle', uz: 'to‘g‘ri to‘rtburchak' },
  { en: 'Rectangular', uz: 'to‘g‘ri to‘rtburchakli' },
  { en: 'Triangle', uz: 'uchburchak' },
  { en: 'Triangular', uz: 'uchburchakli' },
  { en: 'Oval', uz: 'oval' },
  { en: 'Point', uz: 'nuqta' },
  { en: 'Pointed', uz: 'nuqtali' },
  { en: 'Straight', uz: 'to‘g‘ri, tekis' },
  { en: 'Curved', uz: 'qavariq' },
  { en: 'Parallel', uz: 'parallel' },
  { en: 'Vertical', uz: 'tik' },
  { en: 'Diagonal', uz: 'diagonal' },
  { en: 'Shape', uz: 'shakl' },
  { en: 'Look', uz: 'qaramoq' },
  { en: 'Glance', uz: 'tez qaramoq' },
  { en: 'See', uz: 'ko‘rish' },
  { en: 'Watch', uz: 'tomosha qilish' },
  { en: 'Appear', uz: 'paydo bo‘lish' },
  { en: 'Disappear', uz: 'ko‘rinmay ketish' },
  { en: 'Stare', uz: 'tikilmoq' },
  { en: 'Notice', uz: 'sezmoq' },
  { en: 'Observant', uz: 'kuzatuvchi, ziyrak' },
  { en: 'Hear', uz: 'to‘satdan eshitib qolish' },
  { en: 'Sound like', uz: 'kabi ovoz' },
  { en: 'Listen', uz: 'eshitmoq, tinglamoq' },
  { en: 'Overhear', uz: 'bilmasdan eshitib qolish' },
  { en: 'Smell', uz: 'hidlamoq, hid taratmoq' },
  { en: 'Smell like sth', uz: 'nimagadir o‘xshab hid taralish' },
  { en: 'Stink', uz: 'sassiq hid' },
  { en: 'Flavour', uz: 'ta’m, mazza' },
  { en: 'Taste', uz: 'ta’mi, mazzasi' },
  { en: 'Salty', uz: 'sho‘r' },
  { en: 'Bland', uz: 'yumshoq' },
  { en: 'Touch', uz: 'ushlamoq' },
  { en: 'Feel', uz: 'his qilish' },
  { en: 'Damp', uz: 'nam' },
  { en: 'Feel like sth', uz: 'kabi his' },
  { en: 'Press', uz: 'bosmoq' },
  { en: 'Grab', uz: 'tortib olish' },
  { en: 'Tap', uz: 'teginish' },
  { en: 'Rub', uz: 'ishqalamoq' },
  { en: 'Illustrate', uz: 'ko‘rsatish, tasvirlab berish' },
  { en: 'Illustration', uz: 'rasm, tasvir' },
  { en: 'Scene', uz: 'sahna' },
  { en: 'Leisure', uz: 'bo‘sh vaqt' },
  { en: 'Industry', uz: 'sanoat' },
  { en: 'Industrial', uz: 'sanoatga oid' },
  { en: 'In the distance', uz: 'masofadan, nimadandir uzoqda' },
  { en: 'Just', uz: 'shunchaki' },
  { en: 'Ignore', uz: "e'tibor bermaslik, mensimaslik" },
  { en: 'Even', uz: 'hatto' },
  { en: 'Sense', uz: 'his qilish' },
  { en: 'Warmth', uz: 'issiqlik' },
  { en: 'Bright', uz: 'yorqin' },
  { en: 'Dark', uz: "qorong'u" },
  { en: 'Brightness', uz: 'yorqinlik' },
  { en: 'In the foreground', uz: 'oldinda' },
  { en: 'Background', uz: 'orqa tomoni, orqa fon' },
  { en: 'In the bottom left-hand corner', uz: 'chap taraf past burchak' },
  { en: 'In the right-hand top corner', uz: "o'ng tepa taraf burchak" },
  { en: 'On the left-hand side', uz: 'chap qo‘l tomon' },
  { en: 'On the right-hand side', uz: "o'ng qo‘l tomon" },
  { en: 'In the middle/center of', uz: 'o‘rta' },
  { en: 'Painter', uz: 'rassom' },
  { en: 'Paint', uz: 'bo‘yamoq, chizmoq' },
  { en: 'Squeeze', uz: 'siqish, ezish' },
  { en: 'Tube', uz: 'turba' },
  { en: 'Tear up', uz: 'yirtish' },
  { en: 'Drag', uz: 'sudramoq, tortmoq' },
  { en: 'Cabinet', uz: 'javon' },
  { en: 'Knock', uz: 'taqillatish' },
  { en: 'Scratch', uz: 'timdalash, tirnamoq' },
  { en: 'Lid', uz: 'qopqoq' },
  { en: 'Shake', uz: 'silkitmoq' },
  { en: 'Smash', uz: 'sindirmoq' },
  { en: 'Fold', uz: 'buklamoq' },
  { en: 'In half/in two', uz: 'ikkiga, yarmidan' },
  { en: 'Spray', uz: 'sepish' },
  { en: 'Leaf', uz: 'barg' },
  { en: 'Whisper', uz: 'pichirlamoq' },
  { en: 'Cry', uz: 'yig‘lash' },
  { en: 'Scream', uz: 'baqirmoq, qichqirmoq' },
  { en: 'Burst into tears', uz: 'to‘satdan yig‘lash' },
  { en: 'Burst out laughing', uz: 'to‘satdan kulishni boshlash' },
  { en: 'Sigh', uz: 'harsinish' },
  { en: 'Sneeze', uz: 'aksirmoq' },
  { en: 'Loud', uz: 'baland' },
  { en: 'Silent', uz: 'jim' },
  { en: 'Silence', uz: 'jimlik' },
  { en: 'Against the law', uz: 'qonunga qarshi' },
  { en: 'Obey the law', uz: 'qonunga bo‘ysunish' },
  { en: 'Steal', uz: 'o‘g‘irlamoq' },
  { en: 'Property', uz: 'mulk' },
  { en: 'Commit a crime', uz: 'Jinoyat sodir qilish' },
  { en: 'Break the law', uz: 'Qonunni buzish' },
  { en: 'Offence', uz: 'Jinoyat' },
  { en: 'Crime', uz: 'Jinoyat' },
  { en: 'Offender', uz: 'Jinoyatchi' },
  { en: 'A criminal', uz: 'Jinoyatchi' },
  { en: 'Minor', uz: 'Kichik, uncha jiddiy bo‘lmagan' },
  { en: 'Serious', uz: 'Jiddiy' },
  { en: 'Violent', uz: 'Zo‘ravon' },
  { en: 'Violence', uz: 'Zo‘ravonlik' },
  { en: 'Kill', uz: 'O‘ldirmoq' },
  { en: 'Attack', uz: 'Hujum qilish' },
  { en: 'Go to prison', uz: 'Qamalish, qamoqqa borish' },
  { en: 'Theft', uz: 'O‘g‘irlik' },
  { en: 'Thief', uz: 'O‘g‘ri' },
  { en: 'Steal', uz: 'O‘g‘irlamoq' },
  { en: 'Robbery', uz: 'Zo‘ravonlik bilan o‘g‘irlik' },
  { en: 'Robber', uz: 'Qaroqchi, o‘g‘ri' },
  { en: 'Burglary', uz: 'Biror joyga noqonuniy kirib o‘g‘irlik qilish' },
  { en: 'Burglar', uz: 'Noqonuniy kiruvchi o‘g‘ri' },
  { en: 'Shoplifting', uz: 'Do‘kondan o‘g‘irlik' },
  { en: 'Shoplifter', uz: 'Do‘kon o‘g‘risi' },
  { en: 'Mugging', uz: 'Hujum qilib o‘g‘irlik qilish' },
  { en: 'Mugger', uz: 'Hujum qilib o‘g‘irlaydigan o‘g‘ri' },
  { en: 'Assault', uz: 'Jismonan jarohatlash' },
  { en: 'Attacker', uz: 'Hujumchi' },
  { en: 'Stab', uz: 'Pichoqlamoq, pichoq tiqish' },
  { en: 'Murder', uz: 'Kimnidir ataylab o‘ldirish' },
  { en: 'Deliberately', uz: 'Ataylab' },
  { en: 'Murderer', uz: 'Qotil' },
  { en: 'Report', uz: 'Hisobot berish' },
  { en: 'Victim', uz: 'Qurbon, jabrlanuvchi' },
  { en: 'Investigate', uz: 'Tergov qilish' },
  { en: 'Witness', uz: 'Guvoh' },
  { en: 'May', uz: 'Mumkin' },
  { en: 'Take place', uz: 'Sodir bo‘lish' },
  { en: 'Catch sb', uz: 'Kimnidir tutish' },
  { en: 'Suspect', uz: 'Gumonlanuvchi, shubhali' },
  { en: 'Evidence', uz: 'Dalil, isbot' },
  { en: 'Charge sb', uz: 'Kimnidir ayblash' },
  { en: 'Judge', uz: 'Qaror qabul qilish' },
  { en: 'Trial', uz: 'Sud jarayoni' },
  { en: 'Try', uz: 'Harakat qilish, urinish' },
  { en: 'Jury', uz: 'Hakamlar hay’ati' },
  { en: 'Prosecution', uz: 'Taqib qilish' },
  { en: 'Accuse', uz: 'Ayblash' },
  { en: 'Defendant', uz: 'Sudlanuvchi' },
  { en: 'Defence', uz: 'Himoya, mudofaa' },
  { en: 'Innocent', uz: 'Aybsiz' },
  { en: 'Guilty', uz: 'Aybdor' },
  { en: 'Sentence', uz: 'Hukm qilish' },
  { en: 'Get a fine', uz: 'Jarima olish' },
  { en: 'Prison sentence', uz: 'Qamoq jazosi' },
  { en: 'Prove', uz: 'Isbotlash' },
  { en: 'Fine', uz: 'Jarima' },
  { en: 'Suffer from', uz: '…dan aziyat chekish, azoblanish' },
  { en: 'Infectious', uz: 'Yuqumli' },
  { en: 'Infection', uz: 'Infeksiya' },
  { en: 'Disease', uz: 'Kasallik' },
  { en: 'Asthma', uz: 'Nafas olish qiyin bo‘lgan kasallik' },
  { en: 'Increase', uz: 'Oshirmoq, ko‘paytirish' },
  { en: 'Decrease', uz: 'Kamaytirish' },
  { en: 'Breathe in', uz: 'Nafas olish' },
  { en: 'Breathe out', uz: 'Nafas chiqarish' },
  { en: 'Lungs', uz: 'O‘pka' },
  { en: 'Allergy', uz: 'Allergiya' },
  { en: 'Allergic', uz: 'Allergiyasi bor' },
  { en: 'Dramatic', uz: 'Jiddiy, og‘ir, mushkul' },
  { en: 'Obesity', uz: 'Semizlik' },
  { en: 'Obese', uz: 'Semiz' },
  { en: 'Lead to sth', uz: 'Nimadirga sabab bo‘lish yoki boshlash' },
  { en: 'Heart attack', uz: 'Yurak huruji' },
  { en: 'Diabetes', uz: 'Saharlik kasalligi' },
  { en: 'Diabetic', uz: 'Diabetik' },
  { en: 'Depression', uz: 'Umidsizlik, hafalik' },
  { en: 'Depressed', uz: 'Hafa, tushkun' },
  { en: 'Disabled', uz: 'Nogiron' },
  { en: 'Blind', uz: "Ko'r" },
  { en: 'Deaf', uz: 'Kar' },
  { en: 'Speak up', uz: 'Baland gapirish' },
  { en: 'Go deaf', uz: "Kar bo'lish" },
  { en: 'Stroke', uz: 'Shol, insult' },
  { en: 'Have a stroke', uz: 'Insulti bor' },
  { en: 'Heart disease', uz: 'Yurak kasalligi' },
  { en: 'Brain', uz: 'Miya' },
  { en: 'Cancer', uz: 'Saraton' },
  { en: 'Arthritis', uz: "Bo'g'imlar yallig'lanishi" },
  { en: 'Memory loss', uz: "Xotira yo'qolishi" },
  { en: 'Election', uz: 'Saylov' },
  { en: 'Elect', uz: 'Saylamoq' },
  { en: 'Vote for sb', uz: 'Ovoz berish' },
  { en: 'Political party', uz: 'Siyosiy partiya' },
  { en: 'In power', uz: 'Hokimiyatda' },
  { en: 'Politician', uz: 'Siyosatchi' },
  { en: 'Government', uz: 'Hukumat' },
  { en: 'Prime minister', uz: 'Bosh vazir' },
  { en: 'Objective', uz: 'Maqsad' },
  { en: 'Aim', uz: 'Maqsad' },
  { en: 'Goal', uz: 'Maqsad' },
  { en: 'Announcement', uz: "E'lon" },
  { en: 'Priority', uz: 'Afzallik' },
  { en: 'Focus on sth', uz: 'Diqqat qaratish' },
  { en: 'Campaign', uz: 'Kampaniya' },
  { en: 'Opposition', uz: 'Qarama-qarshilik' },
  { en: 'Conflict', uz: 'Ziddiyat' },
  { en: 'Bomb', uz: 'Bomba' },
  { en: 'Explosion', uz: 'Portlash' },
  { en: 'Dozen', uz: '12 ta' },
  { en: 'Soldier', uz: 'Askar' },
  { en: 'Army', uz: 'Armiya' },
  { en: 'Fight', uz: 'Jang qilish' },
  { en: 'Battle', uz: 'Urush' },
  { en: 'Capture', uz: 'Ushlash' },
  { en: 'Enemy', uz: 'Dushman' },
  { en: 'Surrender', uz: "Taslim bo'lish" },
  { en: 'Crisis', uz: 'Inqiroz' },
  { en: 'Civil war', uz: 'Fuqarolik urushi' },
  { en: 'Break out', uz: 'Boshlanish' },
  { en: 'Ally', uz: 'Ittifoqdosh' },
  { en: 'Leader', uz: 'Boshlovchi' },
  { en: 'Negotiate', uz: 'kelishmoq' },
  { en: 'Peace settlement', uz: 'tinchlik kelishuvi' },
  { en: 'Peace', uz: 'tinchlik' },
  { en: 'Side', uz: 'tomon, taraf' },
  { en: 'Ceasefire', uz: 'sulh' },
  { en: 'Willing to do sth', uz: 'nimadir qilishni hohlamoq' },
  { en: 'Compromise', uz: 'qabul qilish' },
  { en: 'Invade', uz: 'bostirib kirish' },
  { en: 'Defeat', uz: 'yutqizish, mag‘lub bo‘lish' },
  { en: 'Invasion', uz: 'bosqin' },
  { en: 'Discover', uz: 'topib olish, kashf qilish' },
  { en: 'Discovery', uz: 'kashfiyot' },
  { en: 'Revolution', uz: 'o‘zgarish' },
  { en: 'Republic', uz: 'respublika' },
  { en: 'Gain independence', uz: 'mustaqillikka erishmoq' },
  { en: 'Independent', uz: 'mustaqil' },
  { en: 'Establish', uz: 'boshlamoq, o‘rnatmoq, tiklamoq' },
  { en: 'Establishment', uz: 'o‘rnatish, barpo etish' },
  { en: 'President', uz: 'president' },
  { en: 'Assassinate', uz: 'suiqasd qilish' },
  { en: 'Assassination', uz: 'suiqasd' },
  { en: 'Attempt to do sth', uz: 'nimadir qilishga harakat qilish' },
  { en: 'Release sb', uz: 'qo‘yib yuborish, ozod qilish' },
  { en: 'Release', uz: 'qo‘yib yuborish' },
  { en: 'Whole', uz: 'butun' },
  { en: 'Journalism', uz: 'jurnalistika' },
  { en: 'Journalist', uz: 'jurnalist' },
  { en: 'Editor', uz: 'muharrir' },
  { en: 'Edit', uz: 'tahrir qilish, montaj qilish' },
  { en: 'Daily', uz: 'har kungi' },
  { en: 'Publish', uz: 'chop etish' },
  { en: 'Several', uz: 'bir qancha' },
  { en: 'National', uz: 'milliy' },
  { en: 'International', uz: 'xalqaro' },
  { en: 'Headline', uz: 'sarlavha' },
  { en: 'Current affairs', uz: 'joriy ishlar' },
  { en: 'Section', uz: 'qism, bo‘lim' },
  { en: 'Culture', uz: 'madaniyat' },
  { en: 'Decline', uz: 'pasayish' },
  { en: 'The press', uz: 'matbuot' },
  { en: 'Axe', uz: 'bolta' },
  { en: 'Protest', uz: 'norozilik bildirmoq' },
  { en: 'Scare', uz: 'qo‘rqmoq, xavotir olish' },
  { en: 'Afraid', uz: 'qo‘rqqan, cho‘chigan' },
  { en: 'Worried', uz: 'xavotir olgan' },
  { en: 'Bomb scare', uz: 'bomba qo‘rquvi' },
  { en: 'Health scare', uz: 'sog‘liq qo‘rquvi' },
  { en: 'Food scare', uz: 'ovqat qo‘rquvi' },
  { en: 'Demonstrate', uz: 'ko‘rsatmoq' },
  { en: 'Demonstration', uz: 'namoyish' },
  { en: 'Threat', uz: 'tahdid, po‘pisa' },
  { en: 'Threaten', uz: 'tahdid qilish' },
  { en: 'Claim', uz: 'tasdiqlamoq' },
  { en: 'Promise', uz: 'va’da berish' },
  { en: 'Pension', uz: 'pensiya' },
  { en: 'Regularly', uz: 'muntazam ravishda' },
  { en: 'Pensioner', uz: 'pensiyaner' },
  { en: 'Pledge', uz: 'garov, garovga qo‘yish' },
  { en: 'Aid', uz: 'yordam berish' },
  { en: 'The equivalent of sth', uz: 'miqdor' },
  { en: 'Award', uz: 'mukofot' },
  { en: 'Prize', uz: 'sovrin, mukofot' },
  { en: 'Individual', uz: 'shaxs, kishi' },
  { en: 'Achievement', uz: 'g‘alaba, yutuq, muvaffaqiyat' },
  { en: 'Winner', uz: 'g‘olib' },
  { en: 'Outstanding', uz: 'ajoyib' },
  { en: 'Director', uz: 'rahbar, boshliq' },
  { en: 'Direct', uz: 'to‘g‘ridan-to‘g‘ri' },
  { en: 'Producer', uz: 'ishlab chiqaruvchi' },
  { en: 'Produce', uz: 'ishlab chiqarish' },
  { en: 'Role', uz: 'ijro' },
  { en: 'Leading role', uz: 'bosh ijro' },
  { en: 'Editing', uz: 'montaj qilish' },
  { en: 'Edit', uz: 'tahrirlash' },
  { en: 'Extraordinary', uz: 'g‘ayrioddiy, o‘zgacha' },
  { en: 'Incredible', uz: 'aqilga sig‘mas, ajoyib' },
  { en: 'Ordinary', uz: 'oddiy, odatiy' },
  { en: 'Performance', uz: 'ijro' },
  { en: 'Grip', uz: 'ushlash, bosib olish' },
  { en: 'Entertaining', uz: 'qiziqarli' },
  { en: 'Drama', uz: 'drama' },
  { en: 'Fan', uz: 'muhlis' },
  { en: 'Movie', uz: 'kino' },
  { en: 'Plot', uz: "ma'no" },
  { en: 'Disappointing indeed', uz: 'haqiqatdan ham umidsizlik' },
  { en: 'Dramatic', uz: 'jiddiy' },
  { en: 'Swear', uz: 'so‘kmoq, qasam ichmoq' },
  { en: 'Unsuitable', uz: 'nomunosib, yarashmaydigan' },
  { en: 'Disgusting', uz: 'jirkanch' },
  { en: 'Suitable', uz: 'mos' },
  { en: 'Exhibition', uz: 'ko‘rgazma' },
  { en: 'Variety', uz: 'har xil' },
  { en: 'Vary', uz: 'o‘zgartirmoq, farqi bor' },
  { en: 'Drawing', uz: 'qalamda chizilgan narsa' },
  { en: 'On display', uz: 'ekranda' },
  { en: 'On show', uz: 'sahnada' },
  { en: 'Style', uz: 'uslub' },
  { en: 'Work of art', uz: 'sanat asari' },
  { en: 'Realistic', uz: 'haqiqiy amaliy' },
  { en: 'Realism', uz: 'amaliylik' },
  { en: 'Skilled', uz: 'qobiliyatli' },
  { en: 'Expert', uz: 'mutaxassis' },
  { en: 'Technique', uz: 'texnika' },
  { en: 'Create', uz: 'yaratmoq' },
  { en: 'Sort', uz: 'saralash, tur, nav' },
  { en: 'Landscape', uz: 'manzara' },
  { en: 'Oil', uz: "yog'" },
  { en: 'Watercolour', uz: 'akvarel' },
  { en: 'Abstract', uz: 'aniq bo‘lmagan, mavhum' },
  { en: 'Out of focus', uz: 'diqqatdan tashqarida' },
  { en: 'In focus', uz: 'diqqat markazida' },
  { en: 'Focus on sth', uz: 'nimagadir diqqat qaratish' },
  { en: 'Transfer sth from sth to sth', uz: "nimadirdan nimagadir o'tkazish" },
  { en: 'Develop a film', uz: 'film ishlab chiqish' },
  { en: 'Automatic', uz: 'avtomatlashtirilgan' },
  { en: 'Studio', uz: 'studiya' },
  { en: 'Take a picture', uz: 'rasm olish' },
  { en: 'Photos', uz: 'rasm' },
  { en: 'Photography', uz: 'rasm' },
  { en: 'Photographer', uz: 'suratchi' },
  { en: 'Amateur', uz: 'havaskor' },
  { en: 'Musical instrument', uz: 'musiqa asbobi' },
  { en: 'Musician', uz: 'musiqachi' },
  { en: 'Composer', uz: 'bastakor' },
  { en: 'Lead singer', uz: 'bosh qo‘shiqchi' },
  { en: 'Songwriter', uz: 'qo‘shiq yozuvchi' },
  { en: 'Band', uz: 'musiqiy guruh' },
  { en: 'Group', uz: 'guruh' },
  { en: 'Conductor', uz: 'dirijyor' },
  { en: 'Orchestra', uz: 'orkestr' },
  { en: 'Solo artist', uz: 'yakka artist' },
  { en: 'Admire sb', uz: 'hurmat qilish, hayron qolish' },
  { en: 'Admiration', uz: 'hayrat' },
  { en: 'Influence sb/sth', uz: 'kimga/yokim nimagadir ta’sir qilish' },
  { en: 'Influence', uz: 'ta’sir' },
  { en: 'Record sth', uz: 'yozib olish' },
  { en: 'Recording', uz: 'yozish' },
  { en: 'Album', uz: 'albom, kolleksiya' },
  { en: 'Release sth', uz: 'qo‘yib yuborish' },
  { en: 'Appeal to sb', uz: 'yoqish, qiziqtirish' },
  { en: 'Voice', uz: 'ovoz' },
  { en: 'Talented at', uz: 'talantli, iqtidorli' },
  { en: 'Talent', uz: 'iqtidor' },
  { en: 'Melody', uz: 'ohang, navo, kuy' },
  { en: 'Tune', uz: 'kuylash' },
  { en: 'Lyrics', uz: 'qo‘shiq so‘zlari' },
  { en: 'Alive', uz: 'tirik' },
  { en: 'Referee', uz: 'hakam' },
  { en: 'Linesman', uz: 'ofsayd belgilovchi hakam' },
  { en: 'Manager', uz: 'menejer' },
  { en: 'Coach', uz: 'murabbiy' },
  { en: 'Captain', uz: 'kapitan' },
  { en: 'Spectators', uz: 'tomoshabinlar' },
  { en: 'Supporters', uz: 'qo‘llab-quvvatlovchilar' },
  { en: 'Commentator', uz: 'sharhlovchi' },
  { en: 'Assistant', uz: 'yordamchi' },
  { en: 'Player', uz: 'o‘yinchi' },
  { en: 'Golfer', uz: 'golfchi' },
  { en: 'Swimmer', uz: 'suzuvchi' },
  { en: 'Driver', uz: 'haydovchi' },
  { en: 'Boxer', uz: 'bokschi' },
  { en: 'Skier', uz: 'chang‘ichi' },
  { en: 'Athletics', uz: 'yengil atletika' },
  { en: 'Athlete', uz: 'sportchi' },
  { en: 'Stadium', uz: 'stadion' },
  { en: 'Ground', uz: 'yer' },
  { en: 'Club', uz: 'klub' },
  { en: 'Capacity', uz: "sig'im, hajim" },
  { en: 'Circuit', uz: 'sxema' },
  { en: 'Lap', uz: "turpoq yo'l" },
  { en: 'Court', uz: 'tennis maydoni' },
  { en: 'Worldwide', uz: "dunyo bo'ylab" },
  { en: 'All over the world', uz: "dunyo bo'ylab" },
  { en: 'Construct', uz: 'qurmoq' },
  { en: 'Construction', uz: 'qurilish' },
  { en: 'Championship', uz: 'chempiyanat, birinchilik' },
  { en: 'Interrupt', uz: "biror narsani to'xtatish" },
  { en: 'Standard', uz: 'standart, mezon' },
  { en: 'Minimum', uz: 'eng kami' },
  { en: 'Maximum', uz: "eng ko'pi" },
  { en: 'Long', uz: 'uzun' },
  { en: 'Wide', uz: 'keng' },
  { en: 'Deep', uz: 'chuqur' },
  { en: 'Length', uz: 'uzunlik' },
  { en: 'Width', uz: 'kenglik' },
  { en: 'Depth', uz: 'chuqurlik' },
  { en: 'Take place', uz: "sodir bo'lish, bo'lib o'tish" },
  { en: 'Competition', uz: 'musobaqa' },
  { en: 'Competitor', uz: 'musobaqachi' },
  { en: 'Compete', uz: 'musobaqalashish' },
  { en: 'Race', uz: 'poyga' },
  { en: 'Take part in sth', uz: 'nimadirda ishtirok etish' },
  { en: 'Participate', uz: 'ishtirok etish' },
  { en: 'Medal', uz: 'medal' },
  { en: 'Professional', uz: 'professional' },
  { en: 'Amateur', uz: 'havaskor' },
  { en: 'Record', uz: 'rekord' },
  { en: 'Holds the record', uz: 'rekordni ushlab turish' },
  { en: 'One-sided', uz: 'bir tomonlama' },
  { en: 'Contest', uz: 'musobaqa' },
  { en: 'Defeated', uz: "mag'lubiyatga uchragan" },
  { en: 'Defeat', uz: "mag'lub bo'lish" },
  { en: 'Semi-final', uz: 'yarim final' },
  { en: 'Final', uz: 'final' },
  { en: 'Resistance', uz: 'qarshilik' },
  { en: 'Brilliant', uz: 'ajoyib' },
  { en: 'Critical', uz: 'jiddiy, muhim' },
  { en: 'Criticize', uz: 'tanqid qilish' },
  { en: 'Performance', uz: 'ijro, ishlash' },
  { en: 'Praised', uz: 'maqtovli' },
  { en: 'Praise', uz: 'maqtamoq' },
  { en: 'Perform', uz: 'ijro etish, bajarish' },
  { en: 'Opponent', uz: 'raqib' },
  { en: 'Outstanding', uz: 'ajoyib' },
  { en: 'Favourite', uz: 'sevimli' },
  { en: 'Overall', uz: 'umuman olganda' },
  { en: 'Achievement', uz: 'muvaffaqiyat' },
  { en: 'Beat', uz: 'urmoq, yutmoq' },
  { en: 'Outsider', uz: 'begona' },
  { en: 'Resist', uz: 'qarshilik qilish' },
  { en: 'Reference book', uz: "ma'lumotnoma" },
  { en: 'Encyclopedia', uz: 'entsiklopediya' },
  { en: 'Manual', uz: "qo'llanma" },
  { en: 'Catalogue', uz: 'katalog' },
  { en: 'Pleasure', uz: 'xursandchilik, zavq' },
  { en: 'Poetry', uz: "she'riyat" },
  { en: 'Alphabetical', uz: 'alifbo tartibida' },
  { en: 'Novel', uz: 'roman' },
  { en: 'Mystery', uz: 'sir' },
  { en: 'Science fiction', uz: 'ilmiy fantastika' },
  { en: 'Ski-fi', uz: 'ilmiy fantastika' },
  { en: 'Non-fiction', uz: "badiiy bo'lmagan" },
  { en: 'Biography', uz: 'biografiya' },
  { en: 'Autobiography', uz: 'avtobiografiya' },
  { en: 'Title', uz: 'sarlavha' },
  { en: 'Cover', uz: "muqova, o'ramoq" },
  { en: 'Attract', uz: 'jalb qilish' },
  { en: 'Attention', uz: "diqqat, e'tibor" },
  { en: 'Browse', uz: "ko'rib chiqish" },
  { en: 'Paperback', uz: "qog'oz muqovasi" },
  { en: 'Hardback', uz: 'qattiq muqovali' },
  { en: 'Readable', uz: "o'qish mumkin bo'lgan" },
  { en: 'Gift', uz: "sovg'a" },
  { en: 'Present', uz: "hozirgi, sovg'a" },
  { en: 'Author', uz: 'muallif' },
  { en: 'Look through sth', uz: "nimadir orqali qarash, tez o'qish" },
  { en: 'Skim', uz: "ajratib olish, yuzaki o'qish" },
  { en: 'Chapter', uz: 'bob' },
  { en: 'Attract sb’s attention', uz: 'kimningdir diqqatini qaratish' },
  { en: 'Fascinating', uz: 'maftunkor' },
  { en: 'Well written', uz: 'yaxshi yozilgan' },
  { en: 'Well informed', uz: "Yaxshi ma'lumotga ega" },
  { en: 'Well known', uz: 'Taniqli' },
  { en: 'Participate (in sth)', uz: 'Ishtirok etish (in sth)' },
  { en: 'Occasion', uz: 'Voqea' },
  { en: 'Fireworks', uz: 'Salyut' },
  { en: 'Ton', uz: 'Tonna' },
  { en: 'Throw sth', uz: 'Otish, uloqtirish' },
  { en: 'Bloom', uz: 'Gullash' },
  { en: 'Blossom', uz: 'Gullash' },
  { en: 'Approach', uz: 'Yondashuv, yaqinlashish' },
  { en: 'Light sth up', uz: 'Yoritish' },
  { en: 'Illuminate', uz: 'Yoritish' },
  { en: 'Contest', uz: 'Musobaqa, konkurs' },
  { en: 'Spectacular', uz: 'Ajoyib, tasirchan' },
  { en: 'Entertainment', uz: 'Zavq, o‘yin-kulgu, ko‘ngil ochish' },
  { en: 'Entertainers', uz: 'Tomoshabinlar' },
  { en: 'Wild', uz: 'Yovvoyi' },
  { en: 'Mean a lot of sb', uz: 'Kimgadir juda muhim bo‘lish' },
  { en: 'Neighborhood', uz: 'Turar joy dahasi, mahalla' },
  { en: 'Community', uz: 'Jamiyat' },
  { en: 'Have fun', uz: 'Vaqtni chog‘ o‘tkazish' },
  { en: 'Dress up', uz: 'Kiyinmoq' },
  { en: 'Striking', uz: 'Ajoyib, hayratlanarli' },
  { en: 'Parade', uz: 'Namoyish' },
  { en: 'Carnival', uz: 'Karnaval' },
  { en: 'Success', uz: 'Muoffaqiyat' },
  { en: 'Follow instructions', uz: 'Ko‘rsatmalarga amal qilish' },
  { en: 'Invigilator', uz: 'Kuzatuvchi, nazoratchi' },
  { en: 'Item', uz: 'Buyum, narsa' },
  { en: 'Communicate with sb', uz: 'Kimdir bilan suhbatlashmoq' },
  { en: 'Candidate', uz: 'Nomzod' },
  { en: 'Disqualify sb', uz: 'Huquqdan mahrum etish' },
  { en: 'Cheat', uz: 'Aldamoq' },
  { en: 'Paper', uz: 'Imtihon qog‘ozi' },
  { en: 'Carefully', uz: 'Ehtiyotkorlik bilan' },
  { en: 'Examiner', uz: 'Imtihonchi' },
  { en: 'Planning', uz: 'Rejalashtirish' },
  { en: 'Essential', uz: 'Muhim' },
  { en: 'Devote time to sb', uz: 'Kimdir uchun vaqt ajratish' },
  { en: 'Attitude', uz: 'Muomala, munosabat' },
  { en: 'Relief', uz: 'Yengillik, taskin' },
  { en: 'Academic', uz: 'Ilmiy' },
  { en: 'Undergraduate', uz: 'Tajribasiz, malakasi yo‘q' },
  { en: 'Graduate', uz: 'Tugatmoq, bitirmoq' },
  { en: 'Tutor', uz: 'Repeititor' },
  { en: 'Professor', uz: 'Professor' },
  { en: 'Lecture', uz: 'Leksiya, maruza' },
  { en: 'Seminar', uz: 'Seminar' },
  { en: 'Debate', uz: 'Muhokama, bahslashmoq' },
  { en: 'Attend', uz: 'Bormoq, qatnashmoq' },
  { en: 'Take notes', uz: 'Esga solish uchun yozib qo‘yish' },
  { en: 'Read widely', uz: 'Turli kitoblarni o‘qish' },
  { en: 'Write a thesis', uz: 'Katta yozma ish yozish' },
  { en: 'Do research', uz: 'O‘rganish, tadqiqot qilish' },
  { en: 'Continuous', uz: 'Davomiy, to‘xtovsiz' },
  { en: 'Assessment', uz: 'Baholash' },
  { en: 'Lecturer', uz: 'Leksiyachi, maruzachi' },
  { en: 'Degree', uz: 'Daraja' },
  { en: 'Discuss', uz: 'Muhokama qilish' },
  { en: 'Away from home', uz: 'Uydan uzoqda' },
  { en: 'At home', uz: 'Uyda' },
  { en: 'Freedom', uz: 'Erkinlik' },
  { en: 'Opportunity', uz: 'Imkoniyat' },
  { en: 'Hall of residence', uz: 'Talabalar turar joyi' },
  { en: 'Homesick', uz: 'Uyini sog‘ingan' },
  { en: 'Manage sth', uz: 'Boshqarmoq' },
  { en: 'Fees', uz: 'To‘lovlar' },
  { en: 'Loan', uz: 'Qarz' },
  { en: 'Scholarship', uz: 'Stipendiya' },
  { en: 'Flexible', uz: 'Moslashuvchan, egiluvchan' },
  { en: 'Flexibility', uz: 'Moslashuvchanlik' },
  { en: 'Revision', uz: 'Takrorlash' },
  { en: 'Revise', uz: 'Qayta ko‘rib chiqish' },
  { en: 'On time', uz: 'O‘z vaqtida' },
  { en: 'In time', uz: 'Vaqtdan oldin' },
  { en: 'Based on', uz: 'Asoslangan' },
  { en: 'Vacancy', uz: 'Bo‘sh o‘rin, ochiq joy' },
  { en: 'Valid', uz: "Yaroqli, ta'sirli" },
  { en: 'Advise', uz: 'Maslahat berish' },
  { en: 'Application', uz: 'Ariza, ilova' },
  { en: 'Acknowledge', uz: 'Tan olish, anglamoq' },
  { en: 'Automatically', uz: 'Avtomatik ravishda' },
  { en: 'Interview', uz: 'Uchrashuv, suhbat' },
  { en: 'Contact', uz: 'Aloqaga chiqmoq' },
  { en: 'Assess', uz: 'Baholash' },
  { en: 'Required', uz: 'Majburiy' },
  { en: 'Feedback', uz: 'Fikr-mulohaza' },
  { en: 'Reference', uz: "Ma'lumot" },
  { en: 'Request', uz: 'So‘ramoq' },
  { en: 'Confirmation', uz: 'Tasdiq, tasdiqlash' },
  { en: 'Apply for sth', uz: 'Biror narsaga murojaat qilish' },
  { en: 'Be based somewhere', uz: 'biror joyga asoslanmoq' },
  { en: 'Work permit', uz: 'ishga ruxsat' },
  { en: 'Process', uz: 'jarayon' },
  { en: 'Sector', uz: 'soha' },
  { en: 'Private sector', uz: 'maxfiy soha' },
  { en: 'Experience', uz: "tajriba boshidan o'tkazmoq" },
  { en: 'Qualification', uz: 'malaka, diplom' },
  { en: 'Engineering', uz: 'muhandis, mashinaga oid' },
  { en: 'Military', uz: 'armiya' },
  { en: 'Training', uz: "shug'ullanish" },
  { en: 'Publishing', uz: 'chop etish' },
  { en: 'Manufacturing', uz: 'ishlab chiqarish' },
  { en: 'Train', uz: "shug'ullanmoq" },
  { en: 'Publish', uz: 'chop etish' },
  { en: 'Manufacture', uz: 'ishlab chiqarish' },
  { en: 'Management', uz: 'boshqarish, boshqaruv' },
  { en: 'Manage', uz: 'boshqarmoq' },
  { en: 'Retail', uz: 'savdo' },
  { en: 'Finance', uz: "moliya, mablag'" },
  { en: 'Recruitment', uz: 'ishga qabul qilish' },
  { en: 'Recruit', uz: 'ishga qabul qilmoq' },
  { en: 'Career', uz: 'faoliyat' },
  { en: 'Job', uz: 'ish' },
  { en: 'Profession', uz: 'kasb' },
  { en: 'Plumber', uz: 'santexnik' },
  { en: 'Mechanic', uz: 'mexanik' },
  { en: 'Electrician', uz: 'elektrchi' },
  { en: 'Carpenter', uz: 'duradgor' },
  { en: 'Nanny', uz: 'enaga' },
  { en: 'Travel agent', uz: 'sayohat agenti' },
  { en: 'Arrangement', uz: 'kelishuv' },
  { en: 'Estate agent', uz: 'mulk agenti' },
  { en: 'Importer', uz: 'import qiluvchi' },
  { en: 'Priest', uz: 'ruhoniy' },
  { en: 'Civil servant', uz: 'rasmiy xizmatdagi kishi' },
  { en: 'Particular', uz: 'alohida, maxsus' },
  { en: 'Sales rep/representative', uz: 'savdo vakili' },
  { en: 'Challenging', uz: 'qiyin' },
  { en: 'Challenge', uz: 'qiyinchilik' },
  { en: 'Reward', uz: 'mukofot' },
  { en: 'Promote', uz: "yordam berish, ko'maklashish" },
  { en: 'Transfer', uz: "ko'chirish, o'tkazish" },
  { en: 'Department', uz: "bo'lim" },
  { en: 'Hand in your notice', uz: "tark etish, to'xtatish" },
  { en: 'Resign', uz: "iste'foga chiqish" },
  { en: 'Quit', uz: "to'xtatmoq" },
  { en: 'Make sb redundant', uz: "ishdan bo'shatish" },
  { en: 'Unemployed', uz: 'ishsiz' },
  { en: 'Out of work', uz: 'ishsiz qolgan' },
  { en: 'Elsewhere', uz: 'boshqa joyda' },
  { en: 'Appoint sb', uz: 'ishga tanlash, tayinlash' },
  { en: 'Get a sack', uz: "ishdan bo'shatilish" },
  { en: 'Dismiss', uz: 'rad etish, vazifadan ozod qilish' },
  { en: 'Fire', uz: "ishdan bo'shatish" },
  { en: 'What does your job involve', uz: 'Ishingiz nimalarni talab qiladi?' },
  { en: 'Handle sb/Deal with sb', uz: 'Kimdir bilan kelishish' },
  { en: 'Enquiry', uz: 'so‘rov, savol' },
  { en: 'Inquire', uz: 'so‘ramoq' },
  { en: 'Face to face', uz: 'yuzma-yuz' },
  { en: 'Complaint', uz: 'shikoyat' },
  { en: 'Members of the public', uz: "omma a'zolari" },
  { en: 'Solve a problem', uz: 'muammoga yechim topish' },
  { en: 'Settle', uz: 'hal qilmoq, tartibga solmoq' },
  { en: 'Clerical', uz: 'idora xizmati' },
  { en: 'Duty', uz: 'burch, vazifa' },
  { en: 'Chore', uz: 'yumush' },
  { en: 'In charge of sb', uz: "Kimningdir mas'uliyatida bo‘lish" },
  { en: 'Responsible for sb', uz: "Kimdir uchun mas'ul bo‘lish" },
  { en: 'Make sure', uz: 'Ishonch hosil qilish' },
  { en: 'Responsibility', uz: "mas'uliyat" },
  { en: 'Working', uz: 'ishchi, ishlash' },
  { en: 'Conditions', uz: 'holat, ahvol' },
  { en: 'Stressful', uz: 'hayajonli, xavotirli' },
  { en: 'Shift work', uz: 'smenali ish' },
  { en: 'Overtime', uz: 'ortiqcha ish' },
  { en: 'Work overtime', uz: "qo'shimcha ishlash" },
  { en: 'Bonus', uz: 'bonus, mukofot' },
  { en: 'Sick pay', uz: "kasallik uchun to'lov" },
  {
    en: 'Be entitled to do sth',
    uz: "qonun bo'yicha qilishga ruhsat berilgan",
  },
  { en: 'Union/trade union', uz: 'kasaba uyushmasi' },
  { en: 'Go on strike', uz: 'ish tashlash' },
  { en: 'Annual', uz: 'yillik' },
  { en: 'Turnover', uz: 'aylanma, aylanmasi' },
  { en: 'Operating costs', uz: 'operatsion xarajatlar' },
  { en: 'Inflation', uz: 'pulning qadrsizlanishi' },
  { en: 'Tax', uz: 'soliq' },
  { en: 'Profit', uz: 'foyda' },
  { en: 'Cash', uz: 'naqd pul' },
  { en: 'Flow problems', uz: 'zarar' },
  { en: 'Bank loan', uz: 'bank qarzi' },
  { en: 'Take out loan', uz: 'bankdan qarz olish' },
  { en: 'Insurance', uz: "sug'urta" },
  { en: 'Interest', uz: 'qiziqish, qiziqtirish' },
  { en: 'Rate', uz: 'reyting, daraja' },
  { en: 'Go up', uz: 'osish' },
  { en: 'Increase', uz: 'oshmoq, ko‘tarilmoq' },
  { en: 'Rise', uz: 'osish' },
  { en: 'Grow', uz: 'osish' },
  { en: 'Growth', uz: 'osish' },
  { en: 'Go down', uz: 'pasayish' },
  { en: 'Fall', uz: 'tushish' },
  { en: 'Drop', uz: 'tushish' },
  { en: 'Remain unchanged', uz: 'shundoq qolish, o‘zgarmas qolish' },
  { en: 'Stable', uz: 'barqaror' },
  { en: 'Stability', uz: 'barqarorlik' },
  { en: 'Peak', uz: 'cho‘qqi, eng yuqori nuqta' },
  { en: 'Fluctuate', uz: 'tebranish, silkinish' },
  { en: 'Fluctuation', uz: 'silkinish' },
  { en: 'Slight', uz: 'yengil' },
  { en: 'Gradual', uz: 'bosqichma-bosqich' },
  { en: 'Steady', uz: 'barqaror' },
  { en: 'Significant', uz: 'muhim, ahamiyatli' },
  { en: 'Sharp', uz: 'o‘tkir, keskin' },
  { en: 'Set up a business', uz: 'biznes boshlash' },
  { en: 'Risk', uz: 'xavf, tavakkal' },
  { en: 'Risky', uz: 'xavfli' },
  { en: 'Fail', uz: 'muvaffaqiyatsizlikka uchramoq' },
  { en: 'Go out of business', uz: 'bankrot bo‘lish' },
  { en: 'Quality', uz: 'sifat' },
  { en: 'Goods', uz: 'tovarlar' },
  { en: 'Inadequate', uz: 'yetarli emas, yomon' },
  { en: 'Adequate', uz: 'yetarli, mos' },
  { en: 'Market research', uz: 'bozor tadqiqoti, talablarni o‘rganish' },
  { en: 'Supplier', uz: 'ta’minlovchi' },
  { en: 'Supply', uz: 'ta’minlamoq' },
  { en: 'Stock', uz: 'aksiya' },
  { en: 'Spare', uz: 'zaxira, zahiradagi' },
  { en: 'Asset', uz: 'aktiv, mulk' },
  { en: 'Rival', uz: 'raqib' },
  { en: 'Competitor', uz: 'raqobatchi' },
  { en: 'Employ sb', uz: 'kimnidir ishga olish' },
  { en: 'Employer', uz: 'ish beruvchi' },
  { en: 'Employee', uz: 'xodim' },
  { en: 'Take sb on', uz: 'ishga qabul qilish' },
  { en: 'Struggle', uz: 'kurashmoq' },
  { en: 'Survive', uz: 'tirik qolish' },
  { en: 'Gain sth', uz: 'erishmoq' },
  { en: 'Lose sth', uz: 'yo‘qotish' },
  { en: 'Share', uz: 'ulush, bo‘lishish' },
  { en: 'Break even', uz: 'foyda ham zarar ham qilmaslik' },
  { en: 'Brand', uz: 'brend' },
  { en: 'Shares', uz: 'ulushlar' },
  { en: 'Take over a company', uz: 'kompaniyani boshqarish' },
  { en: 'Manufacturer', uz: 'ishlab chiqaruvchi' },
  { en: 'Producer', uz: 'ishlab chiqaruvchi' },
  { en: 'Produce', uz: 'ishlab chiqarish' },
  { en: 'Found sth', uz: 'asos solish' },
  { en: 'Diversify', uz: 'turli tusga kirish' },
  { en: 'A gap in the market', uz: 'bozorda bo‘sh joy, imkoniyat' },
  { en: 'Potential', uz: 'potensial, imkoniyat' },
  { en: 'Retain sth', uz: 'saqlab qolish' },
  { en: 'Do research', uz: 'o‘rganish, tadqiq qilish' },
  { en: 'Investment', uz: 'sarmoya' },
  { en: 'Invest', uz: 'sarmoya kiritish' },
  { en: 'Crucial', uz: 'muhim, hal qiluvchi' },
  { en: 'Innovative', uz: 'innovatsion' },
  { en: 'Case', uz: 'holat, vaziyat' },
  { en: 'Contract', uz: 'shartnoma' },
  { en: 'Partnership', uz: 'sheriklik, hamkorlik' },
  { en: 'Key', uz: 'kalit, muhim' },
  { en: 'Factor', uz: 'omil, sabab' },
  { en: 'Keep ahead', uz: 'oldinda yurish, ustun bo‘lish' },
  { en: 'Adapt', uz: 'moslashtirish' },
  { en: 'Advertising', uz: 'reklama qilish' },
  { en: 'Advertise', uz: 'reklama qilmoq' },
  { en: 'Strength', uz: 'kuch, qudrat' },
  { en: 'Weakness', uz: 'ojizlik, kuchsizlik' },
  { en: 'Thread', uz: 'xavf, xatar' },
  { en: 'Limited', uz: 'chegaralangan' },
  { en: 'Demand', uz: 'talab, talab qilish' },
  { en: 'Sector', uz: 'sektor, qism' },
  { en: 'Downturn', uz: 'inqiroz, pasayish' },
  { en: 'Upturn', uz: 'ko‘tarilish, o‘sish' },
  { en: 'Reduce', uz: 'kamaytirish' },
  { en: 'Reduction', uz: 'kamayish' },
  { en: 'Opportunity', uz: 'imkoniyat' },
  { en: 'Strategy', uz: 'strategiya, usul' },
  { en: 'Tip', uz: 'maslahat' },
  { en: 'Assume sth', uz: 'taxmin qilish' },
  { en: 'Target', uz: 'maqsad, nishon' },
  { en: 'Ignore', uz: 'e’tibor bermaslik, mensimaslik' },
  { en: 'Respond to', uz: 'javob berish' },
  { en: 'Data', uz: 'ma’lumotlar' },
  { en: 'Gather', uz: 'to‘plamoq, yig‘moq' },
  { en: 'Forecast', uz: 'bashorat qilish' },
  { en: 'Realistic', uz: 'haqiqiy, amaliy' },
  { en: 'Objective', uz: 'maqsadli, obyektiv' },
  { en: 'Evaluate', uz: 'baholash' },
  { en: 'Greedy', uz: "ochko'z" },
  { en: "Can't bear sth", uz: 'biror narsaga chiday olmayman' },
  { en: 'Proposal', uz: 'rasman taklif qilingan reja' },
  { en: 'Propose', uz: 'taklif qilish' },
  { en: 'be meant to', uz: 'nazarda tutilgan' },
  { en: 'Not at all', uz: 'arzimaydi' },
  { en: 'Loathe sth', uz: 'biror narsadan nafratlanish' },
  { en: 'Detest sth', uz: 'biror narsadan nafratlanish' },
  { en: 'Put off', uz: 'keyinga qoldirish, keyinga surish' },
  { en: 'Postpone sth', uz: 'kechiktirish' },
  { en: 'Reckon sth', uz: 'hisoblash' },
  { en: 'In principle', uz: 'umuman olganda' },
  { en: 'The point is', uz: 'Gap shundaki' },
  { en: 'Mature', uz: 'yetuk' },
  { en: 'Oppose to sth', uz: 'biror narsaga qarshi' },
  { en: 'Personally I think', uz: 'shaxsan menimcha' },
  { en: 'It seems to me', uz: 'mening fikrimcha' },
  { en: 'In my opinion', uz: 'mening fikrimcha' },
  { en: "As far as I'm concerned", uz: 'Menga nisbatan' },
  { en: 'Disobedient', uz: 'itoatsiz' },
  { en: 'Obedient', uz: 'itoatkor' },
  { en: 'Obligatory', uz: 'majburiy' },
  { en: 'As an alternative', uz: 'muqobil sifatida' },
  { en: 'Bound to do sth', uz: 'nimadir qilishga majbur' },
  { en: 'Pessimistic', uz: 'umidsizlangan, qayguli' },
  { en: 'Definitely', uz: 'albatta' },
  { en: 'Fancy sb', uz: 'kimnidir jalb qilish' },
  { en: 'Likely to do sth', uz: 'nimadir qilishga ehtimoli bor' },
  { en: 'Unlikely to do sth', uz: 'nimadir qilishga ehtimoldan yiroq' },
  { en: 'Doubt (if/that)', uz: 'shubha' },
  { en: 'Expect sth', uz: 'kutish' },
  { en: 'Might', uz: 'mumkin' },
  { en: 'A chance', uz: 'imkoniyat' },
  { en: 'Disaster', uz: 'falokat' },
  { en: 'Spot', uz: 'nuqta, terida yoqimsiz belgi' },
  { en: 'Similar to sb/sth', uz: "ga o'xshash" },
  { en: 'Alike', uz: "o'xshash" },
  { en: 'Completely different', uz: 'butunlay boshqacha' },
  { en: 'Apart from sb/sth', uz: 'dan tashqari' },
  { en: 'The main difference', uz: 'asosiy farq' },
  { en: 'In comparison with', uz: 'bilan solishtirganda' },
  { en: 'Get together', uz: "birga bo'lish, yig'ilish" },
  { en: 'Available', uz: 'mavjud' },
  { en: 'Tie up', uz: "bog'lash" },
  { en: 'Confirm it with you', uz: 'buni siz bilan tasdiqlang' },
  { en: 'How about ...?', uz: 'qanday...?' },
  { en: 'Instead', uz: "o'rniga" },
  { en: 'Be mad about sth/sb', uz: "nimadandir g'azablanmoq" },
  { en: 'Be crazy about sth/sb', uz: 'aqldan ozish' },
  { en: 'Adore sth', uz: 'sevmok' },
  { en: 'Be keen on sth', uz: 'biror narsaning jinnisi' },
  { en: 'Get to like sth/sb', uz: 'yoqtirib qolish' },
  { en: 'Would rather.....than', uz: "dan ko'ra" },
  { en: 'Apparently', uz: 'aftidan' },
  { en: 'What do you think about...?', uz: 'nima deb oʻylaysiz...?' },
  { en: 'How do you feel about....?', uz: 'nimani his qilyapsiz...?' },
  { en: 'Fault', uz: 'ayb' },
  { en: 'Be to blame for sth', uz: "nimadir uchun aybdor bo'lish" },
  { en: 'In theory', uz: 'nazariy jihatdan' },
  { en: 'Issue', uz: 'muammo yoki muhokama qilinadigan mavzu' },
  { en: 'If you ask me', uz: "so'rasangiz" },
  { en: 'Consider sth', uz: "o'ylamoq, ko'rib chiqmoq" },
  { en: 'Sensible', uz: 'oqilona' },
  { en: 'Silly', uz: 'ahmoq' },
  { en: 'In favour of sth', uz: 'biror narsa foydasiga' },
  { en: 'Against sth', uz: 'biror narsaga qarshi' },
  { en: 'Reduce sth', uz: 'kamaytirish' },
  { en: 'Increase sth', uz: 'oshirish' },
  { en: 'Support sth', uz: "qo'llab-quvvatlash" },
  { en: 'Believe that', uz: 'bunga ishon' },
  { en: 'Dependent on sb/sth', uz: "ga bog'liq" },
  { en: 'Strict', uz: "qattiq qo'l" },
  { en: 'Insist that', uz: 'talab qilish' },
  { en: 'Allow sb to do sth', uz: 'kimgadir ruxsat berish' },
  { en: 'Obey sb/sth', uz: "bo'ysunish" },
  { en: 'Disobey', uz: "bo'ysinmaslik" },
  { en: 'Rule', uz: 'qoida' },
  { en: 'Ban sth', uz: 'taqiqlash' },
  { en: 'Make sb do sth', uz: 'majbur qilish' },
  { en: 'Force sb to do sth', uz: 'kuch bilan majburlash' },
  { en: 'Behaviour', uz: 'xulq-atvor' },
  { en: 'Behave', uz: "o'zini tutish" },
  { en: 'Punish sb', uz: 'kimnidir jazolash' },
  { en: 'Punishment', uz: 'jazo' },
  { en: 'Compulsory', uz: 'majburiy' },
  { en: 'I have no choice/option', uz: "boshqa ilojim yo'q" },
  { en: 'Is forbidden', uz: 'taqiqlangan' },
  { en: "Isn't permitted", uz: 'ruxsat berilmagan' },
  { en: 'Be not allowed to', uz: 'ruxsat berilmagan' },
  { en: 'Optional', uz: 'ixtiyoriy' },
  { en: "It's my choice", uz: 'bu mening tanlovim' },
  { en: "It's up to me", uz: "bu menga bog'liq" },
  { en: 'Option of', uz: 'ning varianti' },
  { en: 'Let', uz: 'ruxsat bering' },
  { en: 'Making plans for sth', uz: 'uchun rejalar tuzish' },
  { en: 'Sort sth out', uz: 'hal qilish, tartibga solish' },
  { en: 'Be going to do sth', uz: 'biror narsa qilmoqchi' },
  { en: 'Except sth', uz: 'narsadan tashqari' },
  {
    en: 'Intend to do sth /doing sth',
    uz: 'biror narsa qilishni niyat qilish',
  },
  { en: 'Hope to do sth', uz: 'biror narsa qilish umidida' },
  { en: 'Go smoothly', uz: 'muammosiz oʻtish' },
  { en: 'Go wrong', uz: 'xato qilish' },
  { en: 'Look forward to sth', uz: 'umid qilib kutib qolmoq' },
  { en: 'Mainstream', uz: 'mashhur' },
  { en: 'Lay off', uz: 'ishdan bo‘shatish' },
  { en: 'Mundane', uz: 'dunyoviy' },
  { en: 'Laborsaving', uz: 'ishni osonlashtiruvchi' },
  { en: 'Beverage', uz: 'ichimlik' },
  { en: 'Felling a little bloated', uz: 'toʻyib, ishib ketgan' },
  { en: 'Bloated', uz: 'ishgan' },
  { en: 'Burn the midnight oil', uz: 'yarim kechagacha oʻqish' },
  { en: 'Coffeeholic', uz: 'kofe jinnisi' },
  { en: 'Resolve', uz: 'hal qilish' },
  { en: 'Settle', uz: 'hal qilish' },
  { en: 'Keep calm', uz: 'xotirjam boʻlish' },
  { en: 'Dissatisfaction', uz: 'qoniqmaslik' },
  { en: 'In person', uz: 'yuzma-yuz gaplashish' },
  { en: 'Lose your temper', uz: 'jahldan chiqish' },
  { en: 'Back sth up', uz: 'qoʻllab-quvvatlash' },
  { en: 'Claim', uz: 'tasdiqlamoq' },
  { en: 'In writing', uz: 'yozma ravishda' },
  { en: 'Consider doing sth', uz: 'nimadir qilishni oʻylash' },
  { en: 'Consideration', uz: 'oʻylash, mulohaza' },
  { en: 'Dreadful', uz: 'dahshatli' },
  { en: 'Bother', uz: 'bezota qilish' },
  { en: 'Fed up with sth', uz: 'nimadandur zerkish' },
  { en: 'Get on sb’s nerves', uz: 'asabga tegish' },
  { en: 'Moan', uz: 'shikoyat qilish, nola' },
  { en: 'Spoil sth', uz: 'buzmoq (spoilt, spoiled)' },
  { en: 'Nuisance', uz: 'asabga tegadigan narsa' },
  { en: 'Mention', uz: 'eslatmoq, qayd etmoq' },
  { en: 'Ruin', uz: 'barbod qilish' },
  { en: 'Atrocious', uz: 'vahshiy, juda yomon' },
  { en: 'Appaling', uz: 'dahshatli' },
  { en: 'Beware of sth', uz: 'nimadandir ehtiyot boʻlish' },
  { en: 'Warning', uz: 'ogohlantirish' },
  { en: 'Cross', uz: 'kesib oʻtish' },
  { en: 'In case of', uz: 'mobodoga' },
  { en: 'Caution', uz: 'ogohlantirish' },
  { en: 'Swallow sth', uz: 'yutmoq' },
  { en: 'Seek sth', uz: 'qidirish' },
  { en: 'Assistance', uz: 'yordam' },
  { en: 'Premises', uz: 'joy, mulk' },
  { en: 'Make sure', uz: 'ishonch hosil qilish' },
  { en: 'Complain', uz: 'shikoyat qilish' },
  { en: 'Guarantee', uz: 'kafolat' },
  { en: 'Expert', uz: 'mutaxassis' },
  { en: 'Happy with sth', uz: 'xursand boʻlish' },
  { en: 'Join', uz: 'qoʻshilish' },
  { en: 'Mind', uz: 'aql, xotira, fikr' },
  { en: 'Danger', uz: 'xavf' },
  { en: 'As a result', uz: 'natijada' },
  { en: 'Due to sth', uz: 'chunki' },
  { en: 'Whats more', uz: 'yana' },
  { en: 'Plus', uz: 'yana' },
  { en: 'As (since for because)', uz: 'chunki' },
  { en: 'Consequently', uz: 'natijada, shu sababli' },
  { en: 'Therefore', uz: 'shuning uchun' },
  { en: 'In addition', uz: 'bunga qoʻshimcha' },
  { en: 'Moreover', uz: 'bundan tashqari' },
  { en: 'Furthermore', uz: 'bundan tashqari' },
  { en: 'Although', uz: 'ga qaramay' },
  { en: 'Despite', uz: 'qaramasdan' },
  { en: 'However', uz: 'lekin, biroq' },
  { en: 'Whereas', uz: 'bo‘lgan paytda' },
  { en: 'On the one hand', uz: 'bir tomondan' },
  { en: 'On the other hand', uz: 'boshqa tarafdan' },
  { en: 'Otherwise', uz: 'aks holda' },
  { en: 'Provided', uz: 'agar' },
  { en: 'As long as', uz: 'agar' },
  { en: 'Unless', uz: 'bo‘lmasa' },
  { en: 'In case', uz: 'mobodoga' },
  { en: 'So that', uz: 'shuning uchun' },
  { en: 'Purpose', uz: 'maqsad' },
  { en: 'Alarming', uz: 'havotirli' },
  { en: 'Alarmed', uz: 'havotirlangan' },
  { en: 'Astonishing', uz: 'hayratlanarli' },
  { en: 'Astonished', uz: 'hayratlangan' },
  { en: 'Satisfying', uz: 'qoniqarli' },
  { en: 'Satisfied', uz: 'qoniqqan' },
  { en: 'Dissatisfied', uz: 'qoniqmagan' },
  { en: 'Adequate', uz: 'yetarli' },
  { en: 'Mixed feelings', uz: 'ijobiy va salbiy hislar' },
  { en: 'Contemporary', uz: 'zamonaviy' },
  { en: 'Old-fashioned', uz: 'eskicha' },
  { en: 'Firm', uz: 'qattiq' },
  { en: 'Soft', uz: 'yumshoq' },
  { en: 'Temporary', uz: 'vaqtinchalik' },
  { en: 'Permanent', uz: 'o‘zgarmas' },
  { en: 'Efficient', uz: 'samarali' },
  { en: 'Inefficient', uz: 'samarasiz' },
  { en: 'Cramped', uz: 'tor' },
  { en: 'Spacious', uz: 'keng' },
  { en: 'Glad', uz: 'xursand' },
  { en: 'Edge', uz: 'chet, qirra' },
  { en: 'Beyond', uz: 'narigi tomonida' },
  { en: 'Rear', uz: 'orqa' },
  { en: 'Front', uz: 'old' },
  { en: 'Face sth', uz: 'nimagadir duch kelish' },
  { en: 'Onto', uz: 'ustiga' },
  { en: 'Beneath', uz: 'ostida' },
  { en: 'Over', uz: 'ustidan' },
  { en: 'Not yet', uz: 'hali emas' },
  { en: 'In the meantime', uz: 'shu paytda' },
  { en: 'Eventually', uz: 'oxir-oqibat' },
  { en: 'These days', uz: 'hozirgi paytda' },
  { en: 'Now and again', uz: 'vaqti-vaqti bilan' },
  { en: 'From time to time', uz: 'vaqti-vaqti bilan' },
  { en: 'Occasionally', uz: 'vaqti-vaqti bilan' },
  { en: 'Remote', uz: 'uzoq' },
  { en: 'Rural', uz: 'qishloqga oid' },
  { en: 'Urban', uz: 'shaharga oid' },
  { en: 'Curious', uz: 'qiziquvchan' },
  { en: 'Vital', uz: 'Muhim' },
  { en: 'Grand', uz: 'Muhim, katta' },
  { en: 'Reasonable', uz: 'Oqilona, xolis' },
  { en: 'Impressed with sth', uz: 'Nimadandur taassurot qoldirish' },
  { en: 'Overall', uz: 'Umumiy' },
  { en: 'Suspicious of sth', uz: 'Shubhali, ishonib bo‘lmaydigan' },
  { en: 'Deserted', uz: 'Tashlandiq, kimsasiz' },
  { en: 'Simple', uz: 'Oddiy, oson' },
  { en: 'Dissapointing', uz: 'Xafa qiladigan' },
  { en: 'Dissapointed', uz: 'Ko‘ngli qogan, sovigan' },
  { en: 'Amazing', uz: 'Hayratlanarli' },
  { en: 'Disgusting', uz: 'Jirkanch' },
  { en: 'Disgusted', uz: 'Jirkanish hissi' },
  { en: 'Amusing', uz: 'Kulgili' },
  { en: 'Amused', uz: 'Quvnoq' },
  { en: 'Embarrassed', uz: 'Uyalgan' },
  { en: 'Embarrassing', uz: 'Uyaltrib yuboradigan' },
  { en: 'Artificial', uz: "Sun'iy" },
  { en: 'Effective', uz: 'Samarali' },
  { en: 'Unexpected', uz: 'Kutilmagan' },
  { en: 'Towards', uz: 'Tomonga' },
  { en: 'Among', uz: 'O‘rtasida' },
  { en: 'Underneath', uz: 'Tagida' },
  { en: 'Already', uz: 'Allaqachon' },
  { en: 'To go', uz: 'Ketishga' },
  { en: 'During', uz: 'Davomida' },
  { en: 'Last', uz: 'Oxirgi, davom etish' },
  { en: 'Throughout', uz: 'Boshdan oxirigacha' },
  { en: 'Recently', uz: 'Yaqinda, hozirgina' },
  { en: 'By chance', uz: 'Tasodifan, bilmasdan' },
  { en: 'On board', uz: 'Kemada, avtobusda, samolyotda' },
  { en: 'On purpose', uz: 'Ataylab' },
  { en: 'At least', uz: 'Kamida' },
  { en: 'At first', uz: 'Boshida' },
  { en: 'In a hurry', uz: 'Shoshilib' },
  { en: 'In advance', uz: 'Oldindan' },
  { en: 'In charge of sb', uz: "Kimdir uchun mas'ul" },
  { en: 'In general', uz: 'Umuman, odatda' },
  { en: 'In public', uz: 'Ommada' },
  { en: 'In the end', uz: 'Oxirida' },
  { en: 'At the end', uz: 'Oxirida (masalan, kino oxirida)' },
  { en: 'Particular', uz: 'Alohida, maxsus' },
  { en: 'Access to sth', uz: 'Nimadandir foydalanish, ulanish' },
  { en: 'Make the most of sth', uz: 'Nimadandir iloji boricha foydalanish' },
  { en: 'Take advantage of sth', uz: 'Foydalanish, manfaat olish' },
  { en: 'Involved in sth', uz: 'Biror narsaga jalb qilingan' },
  { en: 'Capable of sth', uz: 'Nimadadir qodir' },
  { en: 'Approve of sth', uz: "Ma'qullash" },
  { en: 'Get rid of sth', uz: 'Qutulish' },
  { en: 'Care about sth', uz: 'G‘amxo‘rlik qilish' },
  { en: 'Take care of sth', uz: 'G‘amxo‘rlik qilish, parvarish' },
  { en: 'Insist on sth', uz: 'Talab qilish' },
  { en: 'Cope with sth', uz: 'Kurashish, uddalash' },
  { en: 'Manage', uz: 'Boshqarmoq, eplamoq' },
  { en: 'Depend on sth', uz: 'Bog‘liq bo‘lish' },
  { en: 'Secure', uz: 'Xavfsiz, xotirjam' },
  { en: 'Insecure', uz: 'Xavfsiz emas, xotirjamsiz' },
  { en: 'Immoral', uz: 'Axloqsiz, beodob' },
  { en: 'Moral', uz: 'Axloqli, odobli' },
  { en: 'Legible', uz: 'Aniq, tushunarli' },
  { en: 'Illegible', uz: 'O‘qib bo‘lmaydigan, tushunarsiz' },
  { en: 'Relevant', uz: 'O‘rinli' },
  { en: 'Irrelevant', uz: 'O‘rinsiz' },
  { en: 'Fair', uz: 'Adolatli, xolis' },
  { en: 'Unfair', uz: 'Adolatsiz' },
  { en: 'Unacceptable', uz: 'Qabul qilib bo‘lmaydigan' },
  { en: 'Acceptable', uz: "Ma'qul" },
  { en: 'Loyal', uz: 'Sodiq' },
  { en: 'Disloyal', uz: 'Sodiq emas' },
  { en: 'Alcoholic', uz: 'Spirtli' },
  { en: 'Non-alcoholic', uz: 'Spirtsiz' },
  { en: 'Do up', uz: 'Tugmani yoki zamokni taqish' },
  { en: 'Fasten your jacket', uz: 'Ko‘ylagingizni mahkamlang' },
  { en: 'Tie up', uz: 'Bog‘lash (ipini)' },
  { en: 'Fasten', uz: 'Taqish, bog‘lash' },
  { en: 'Untie', uz: 'Yechish, bog‘ini ochish' },
  { en: 'Pack', uz: 'Joylamoq' },
  { en: 'Unpack', uz: 'Ochmoq, joydan chiqarmoq' },
  { en: 'Load', uz: 'Yuklamoq' },
  { en: 'Unload', uz: 'Yukni tushirmoq' },
  { en: 'Plug in', uz: 'Ulash (rozetkaga)' },
  { en: 'Unplug', uz: 'Uzish (rozetkadan)' },
  { en: 'Wrap', uz: 'O‘ramoq' },
  { en: 'Unwrap', uz: 'Yechmoq, o‘ramasini ochmoq' },
  { en: 'Lock', uz: 'Qulfla' },
  { en: 'Unlock', uz: 'Ochmoq (qulfni)' },
  { en: 'Get dressed', uz: 'Kiyinish' },
  { en: 'Get undressed', uz: 'Yechinish' },
  { en: 'Judge', uz: 'Qaror qabul qilish' },
  { en: 'Judgement', uz: 'Qaror, hukm' },
  { en: 'Measure', uz: 'O‘lchamoq' },
  { en: 'Measurement', uz: 'O‘lchov' },
  { en: 'React', uz: 'Munozabat bildirmoq' },
  { en: 'Reaction', uz: 'Reaksiya' },
  { en: 'Extend', uz: 'Uzaytirish' },
  { en: 'Extension', uz: 'kengaytma' },
  { en: 'Interpret', uz: 'tarjima qilish, tushuntirish' },
  { en: 'Interpretation', uz: "e'lon qilish, ko‘rsatish" },
  { en: 'Define', uz: 'tariflamoq, aniqlamoq' },
  { en: 'Disappear', uz: 'ko‘rinmay ketish, g‘oyib bo‘lish' },
  { en: 'Disappearance', uz: 'yo‘qolish' },
  { en: 'Prefer', uz: 'ma’qul ko‘rish' },
  { en: 'Preference', uz: 'ma’qullik, xohish' },
  { en: 'Cruel', uz: 'shafqatsiz' },
  { en: 'Cruelty', uz: 'shafqatsizlik' },
  { en: 'Real', uz: 'haqiqiy' },
  { en: 'Reality', uz: 'haqiqat' },
  { en: 'Gentle', uz: 'yuvosh, xushmuomala' },
  { en: 'Gentleness', uz: 'muloqimlik' },
  { en: 'Kind', uz: 'mehribon' },
  { en: 'Kindness', uz: 'mehr, mehribonlik' },
]
