export const words = [
    { en: 'Growth', uz: "o‘sish" },
    { en: 'Built-up', uz: 'qurilgan' },
    { en: 'A shame', uz: 'uyat' },
    { en: 'Pity', uz: 'achinish, rahm' },
    { en: 'Region', uz: 'mintaqa' },
    { en: 'Substantial', uz: 'muhim' },
    { en: 'Impressive', uz: "ta’sirli" },
    { en: 'Semi-detached', uz: 'yarim bog‘langan' },
    { en: 'Original', uz: 'asli, dastlabki' },
    { en: 'Feature', uz: 'hususiyat, fazilat' },
    { en: 'Lead', uz: 'boshlamoq' },
    { en: 'Walled', uz: 'devor bilan qoplangan' },
    { en: 'Wall', uz: 'devor' },
    { en: 'Brick', uz: 'g‘isht' },
    { en: 'Stone', uz: 'tosh' },
    { en: 'Chimney', uz: 'mo‘ri' },
    { en: 'Roof', uz: 'tom' },
    { en: 'Shutter', uz: 'deraza eshigi' },
    { en: 'Hall', uz: 'zal' },
    { en: 'Passage', uz: 'yo‘lak' },
    { en: 'Corridor', uz: 'kalidor' },
    { en: 'Rubber tyre', uz: 'rezina shina' },
    { en: 'Woollen blanket', uz: 'jun ko‘rpa' },
    { en: 'Plastic toys', uz: 'plastik o‘yinchoqlar' },
    { en: 'Metal ladder', uz: 'metal narvon' },
    { en: 'Wax candle', uz: 'mum sham' },
    { en: 'Silver candlestick', uz: 'kumush shamdon' },
    { en: 'Gold medal', uz: 'oltin medal' },
    { en: 'Cardboard box', uz: 'karton quti' },
    { en: 'Steel pipe', uz: 'po‘lat truba' },
    { en: 'Concrete bridge', uz: 'beton ko‘prik' },
    { en: 'Iron railings', uz: 'temir panjaralar' },
    { en: 'Wooden fence', uz: 'yog‘och to‘siq' },
    { en: 'Circle', uz: 'doira' },
    { en: 'Round', uz: 'yumaloq' },
    { en: 'Spacious', uz: 'keng' },
    { en: 'Enormous', uz: 'katta, ulkan' },
    { en: 'Staircase', uz: 'zina, zinapoya' },
    { en: 'Attic', uz: 'cherdak, bolxona' },
    { en: 'Basement', uz: 'podval' },
    { en: 'Convert sth into sth', uz: 'nimanidir nimagadir o‘zgartirish' },
    { en: 'Separate', uz: 'ajralgan, alohida' },
    { en: 'Cellar', uz: 'yer to‘la' },
    { en: 'Currently', uz: 'hozirda, at the moment' },
    { en: 'Store sth', uz: 'nimanidir saqlab qo‘yish' },
    { en: 'Storage', uz: 'saqlash' },
    { en: 'Lawn', uz: 'gazon, maysazor' },
    { en: 'Drive', uz: 'xiyobon' },
    { en: 'Circular', uz: 'dumaloq' },
    { en: 'Square', uz: 'kvadrat' },
    { en: 'Rectangle', uz: 'to‘g‘ri to‘rtburchak' },
    { en: 'Rectangular', uz: 'to‘g‘ri to‘rtburchakli' },
    { en: 'Triangle', uz: 'uchburchak' },
    { en: 'Triangular', uz: 'uchburchakli' },
    { en: 'Oval', uz: 'oval' },
    { en: 'Point', uz: 'nuqta' },
    { en: 'Pointed', uz: 'nuqtali' },
    { en: 'Straight', uz: 'to‘g‘ri, tekis' },
    { en: 'Curved', uz: 'qavariq' },
    { en: 'Parallel', uz: 'parallel' },
    { en: 'Vertical', uz: 'tik' },
    { en: 'Diagonal', uz: 'diagonal' },
    { en: 'Shape', uz: 'shakl' },
    { en: 'Look', uz: 'qaramoq' },
    { en: 'Glance', uz: 'tez qaramoq' },
    { en: 'See', uz: 'ko‘rish' },
    { en: 'Watch', uz: 'tomosha qilish' },
    { en: 'Appear', uz: 'paydo bo‘lish' },
    { en: 'Disappear', uz: 'ko‘rinmay ketish' },
    { en: 'Stare', uz: 'tikilmoq' },
    { en: 'Notice', uz: 'sezmoq' },
    { en: 'Observant', uz: 'kuzatuvchi, ziyrak' },
    { en: 'Hear', uz: 'to‘satdan eshitib qolish' },
    { en: 'Sound like', uz: 'kabi ovoz' },
    { en: 'Listen', uz: 'eshitmoq, tinglamoq' },
    { en: 'Overhear', uz: 'bilmasdan eshitib qolish' },
    { en: 'Smell', uz: 'hidlamoq, hid taratmoq' },
    { en: 'Smell like sth', uz: 'nimagadir o‘xshab hid taralish' },
    { en: 'Stink', uz: 'sassiq hid' },
    { en: 'Flavour', uz: 'ta’m, mazza' },
    { en: 'Taste', uz: 'ta’mi, mazzasi' },
    { en: 'Salty', uz: 'sho‘r' },
    { en: 'Bland', uz: 'yumshoq' },
    { en: 'Touch', uz: 'ushlamoq' },
    { en: 'Feel', uz: 'his qilish' },
    { en: 'Damp', uz: 'nam' },
    { en: 'Feel like sth', uz: 'kabi his' },
    { en: 'Press', uz: 'bosmoq' },
    { en: 'Grab', uz: 'tortib olish' },
    { en: 'Tap', uz: 'teginish' },
    { en: 'Rub', uz: 'ishqalamoq' },
    { en: 'Illustrate', uz: 'ko‘rsatish, tasvirlab berish' },
    { en: 'Illustration', uz: 'rasm, tasvir' },
    { en: 'Scene', uz: 'sahna' },
    { en: 'Leisure', uz: 'bo‘sh vaqt' },
    { en: 'Industry', uz: 'sanoat' },
    { en: "Industrial", uz: "sanoatga oid" },
    { en: "In the distance", uz: "masofadan, nimadandir uzoqda" },
    { en: "Just", uz: "shunchaki" },
    { en: "Ignore", uz: "e'tibor bermaslik, mensimaslik" },
    { en: "Even", uz: "hatto" },
    { en: "Sense", uz: "his qilish" },
    { en: "Warmth", uz: "issiqlik" },
    { en: "Bright", uz: "yorqin" },
    { en: "Dark", uz: "qorong'u" },
    { en: "Brightness", uz: "yorqinlik" },
    { en: "In the foreground", uz: "oldinda" },
    { en: "Background", uz: "orqa tomoni, orqa fon" },
    { en: "In the bottom left-hand corner", uz: "chap taraf past burchak" },
    { en: "In the right-hand top corner", uz: "o'ng tepa taraf burchak" },
    { en: "On the left-hand side", uz: "chap qo‘l tomon" },
    { en: "On the right-hand side", uz: "o'ng qo‘l tomon" },
    { en: "In the middle/center of", uz: "o‘rta" },
    { en: "Painter", uz: "rassom" },
    { en: "Paint", uz: "bo‘yamoq, chizmoq" },
    { en: "Squeeze", uz: "siqish, ezish" },
    { en: "Tube", uz: "turba" },
    { en: "Tear up", uz: "yirtish" },
    { en: "Drag", uz: "sudramoq, tortmoq" },
    { en: "Cabinet", uz: "javon" },
    { en: "Knock", uz: "taqillatish" },
    { en: "Scratch", uz: "timdalash, tirnamoq" },
    { en: "Lid", uz: "qopqoq" },
    { en: "Shake", uz: "silkitmoq" },
    { en: "Smash", uz: "sindirmoq" },
    { en: "Fold", uz: "buklamoq" },
    { en: "In half/in two", uz: "ikkiga, yarmidan" },
    { en: "Spray", uz: "sepish" },
    { en: "Leaf", uz: "barg" },
    { en: "Whisper", uz: "pichirlamoq" },
    { en: "Cry", uz: "yig‘lash" },
    { en: "Scream", uz: "baqirmoq, qichqirmoq" },
    { en: "Burst into tears", uz: "to‘satdan yig‘lash" },
    { en: "Burst out laughing", uz: "to‘satdan kulishni boshlash" },
    { en: "Sigh", uz: "harsinish" },
    { en: "Sneeze", uz: "aksirmoq" },
    { en: "Loud", uz: "baland" },
    { en: "Silent", uz: "jim" },
    { en: "Silence", uz: "jimlik" },
    { en: "Against the law", uz: "qonunga qarshi" },
    { en: "Obey the law", uz: "qonunga bo‘ysunish" },
    { en: "Steal", uz: "o‘g‘irlamoq" },
    { en: "Property", uz: "mulk" },
  
];